language: python
python:
  - "3.5"
  - "3.6"
# Waiting for "official" support
# https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-405506964
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install codecov -e .[tests]
script:
  - pytest
after_success:
  - codecov
